<?php
/*
*
* Template part
* for displaying on-site department content
*
*/
?>
<?php
  $category = get_the_category();
  $cat_slug =	$category[0]->slug;
  $cat_id =	$category[0]->cat_ID;
  $sidebar_name = 'sidebar-' .	$cat_slug . '-' . $cat_id;
  $has_sidebar = false;
  if ( is_active_sidebar( $sidebar_name ) ) { $has_sidebar = true; }
  /*sidebars are generated by what is in the sidebar widget area */
?>

<div class="small-24 columns">
  <div class="row">
    <div data-swiftype-index='true' class="entry-content <?php echo ($has_sidebar) ? 'medium-16' : 'medium-24'; ?> small-24 columns">
       <?php echo the_content();?>
     </div>
    <?php
      if ( $has_sidebar ) : ?>
        <div id="sidebar" class="medium-8 columns">
          <div class="inner">
            <?php dynamic_sidebar( $sidebar_name ); ?>
          </div>
        </div>
      <?php endif; ?>
  </div>
</div>
